# T87 Booking entries overview

# --- !Ups

create table BOOKING_ENTRY (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  OWNER_ID BIGINT NOT NULL,
  BOOKING_DATE DATE NOT NULL,
  BOOKING_NUMBER INTEGER NOT NULL,
  BRAND_ID BIGINT NOT NULL,
  SUMMARY VARCHAR(254) NOT NULL,
  DESCRIPTION VARCHAR(254),
  URL VARCHAR(254),
  REFERENCE VARCHAR(254),
  REFERENCE_DATE DATE NOT NULL,
  SOURCE_CURRENCY CHAR(3) NOT NULL,
  SOURCE_AMOUNT DECIMAL(13,3) NOT NULL,
  SOURCE_PERCENTAGE INTEGER NOT NULL);

alter table BOOKING_ENTRY add constraint OWNER_FK foreign key(OWNER_ID) references PERSON(ID) on update NO ACTION on delete NO ACTION;
alter table BOOKING_ENTRY add constraint BOOKING_BRAND_FK foreign key(BRAND_ID) references BRAND(ID) on update NO ACTION on delete NO ACTION;

insert into BOOKING_ENTRY (OWNER_ID, BOOKING_DATE, BOOKING_NUMBER, BRAND_ID, SUMMARY, DESCRIPTION,
  URL, REFERENCE, REFERENCE_DATE, SOURCE_CURRENCY, SOURCE_AMOUNT, SOURCE_PERCENTAGE)
select COORDINATOR_ID, current_timestamp, 100000, ID, 'GoDaddy Inc.', 'domain name registration  management30.com.br',
  'http://www.godaddy.com/.....96496987.pdf', '96496987', 2013-08-27, 'USD', 100.00, 100
  from BRAND where NAME='Management 3.0';

# --- !Downs

drop table BOOKING_ENTRY;